source 'https://supermarket.chef.io'

metadata

cookbook 'chef-sugar'
cookbook 'hostsfile'
cookbook 'apt'
cookbook 'yum'
cookbook 'poise-python'
cookbook 'wazuh_filebeat', path: '/home/vagrant/wazuh-chef/cookbooks/wazuh_filebeat/'
