source 'https://supermarket.chef.io'
#cookbook 'wazuh_agent', path '../wazuh_agent'
cookbook 'wazuh_filebeat', path: '../wazuh_filebeat'
cookbook 'wazuh_elastic', path: '../wazuh_elastic'
metadata


cookbook 'chef-sugar'
cookbook 'hostsfile'
cookbook 'apt'
cookbook 'yum'
cookbook 'poise-python'
cookbook 'htpasswd'
