source 'https://rubygems.org'

group :lint do
  gem 'foodcritic', '~> 16.3'
  gem 'rubocop', '~> 1.3', '>= 1.3.1'
  gem 'yaml', '~> 0.1.0'
end

group :unit do
  gem 'berkshelf', '~> 7.1'
  gem 'chefspec', '~> 9.2', '>= 9.2.1'
end

group :kitchen_common do
  gem 'test-kitchen', '~> 2.7', '>= 2.7.2'
end

group :kitchen_vagrant do
  gem 'kitchen-vagrant', '~> 1.7', '>= 1.7.2'
end
