default['wazuh-manager']['version'] = "4.0.1"
default['packages.wazuh.com']['version'] = "4.x"
default['wazuh']['version'] = "4.0"
default['filebeat']['version'] = "7.9.1"
default['elastic']['version'] = "7.x"